AAP-13734 Updates to code samples for sections 2.1.1.4 - 2.1.1.6 in the Installation Guide
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #1192
Opened 2023-07-11 20:34 UTC by jself-sudoku

Updates to code samples in the Red Hat Ansible Automation Platform Installation Guide, specifically in the following sections: 

- [2.1.1.4](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-standlone-platform-ext-database-inventory_platform-install-scenario) 
- [2.1.1.5](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-scenario) 
- [2.1.1.6](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-single-eda-controller-with-internal-db_platform-install-scenario)

2023-07-11 21:06 UTC, jself-sudoku commented
@jamesmarshall24 - Please review.

2023-07-12 18:14 UTC, jamesmarshall24 requested changes

2023-07-12 18:14 UTC, jamesmarshall24 commented on downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
> +
```suggestion
```

2023-07-12 18:14 UTC, jamesmarshall24 commented on downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
> +
```suggestion
```

2023-07-12 18:14 UTC, jamesmarshall24 commented on downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
> +
Only the following should be added to line 43

```
[automationedacontroller]
eda.example.com
```

2023-07-12 18:14 UTC, jamesmarshall24 commented on downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
> +
Only the following should be added to line 46:
```
[automationedacontroller]
eda.example.com
```

2023-07-12 18:17 UTC, jamesmarshall24 commented
@jself-sudoku Also `eda.example.com` was only an example I provided and I'm not sure if that format for examples lines up with the standards of the rest of the documentation. You might want to check with your team regarding example URL formats.

2023-07-27 13:33 UTC, jself-sudoku commented
Thanks, @Alex-Izquierdo! I'll update @jamesmarshall24 and ask him to review also. For now, moving forward with next level reviews.

2023-07-27 17:32 UTC, merged