Added automationedacontoller_pg_* variables
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #1224
Opened 2023-07-18 12:16 UTC by ianf77

Also amended automationhub_pg_host

Event driven ansible inventory variables are missing automationedacontroller_pg_*

https://issues.redhat.com/browse/AAP-14193

2023-07-19 13:10 UTC, jamesmarshall24 requested changes

2023-07-19 13:10 UTC, jamesmarshall24 commented on downstream/modules/platform/ref-eda-controller-variables.adoc
> +Default = `awx`.
```suggestion
Default = `automationedacontroller`.
```

2023-07-19 13:10 UTC, jamesmarshall24 commented on downstream/modules/platform/ref-eda-controller-variables.adoc
> +Default = `awx`.
```suggestion
Default = `automationedacontroller`.
```

2023-07-19 15:36 UTC, jamesmarshall24 approved these changes

2023-07-20 08:12 UTC, ariordan-redhat commented on downstream/modules/platform/ref-eda-controller-variables.adoc
> +| *`automationedacontroller_pg_database`* | The postgres database used by {EDAController.}
```suggestion
| *`automationedacontroller_pg_database`* | The postgres database used by {EDAController}.
```

2023-07-20 08:31 UTC, ariordan-redhat approved these changes

2023-07-20 08:32 UTC, merged