AAP-734: Change all IDS to IDPS
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #170
Opened 2021-09-28 19:14 UTC by lmalivert

Changed all instances of "IDS" to "IDPS"

- Link to Jira: https://issues.redhat.com/browse/AAP-734

- Link to google doc: https://docs.google.com/document/d/1VU0BpbM8RUvchmYmjYdZslkgtvM1BJZV6ZT4Cbrklig/edit#

2021-09-28 20:11 UTC, craig-br requested changes

2021-09-28 20:11 UTC, craig-br commented on downstream/assemblies/security/assembly-idps.adoc
> +You can use Ansible to automate your Intrusion Detection and Prevention Systems (IDPS). For the purpose of this guide, we use Snort as the IDS. Use Ansible automation hub to consume content collectio
`You can use Ansible to automate your Intrusion Detection and Prevention Systems (IDPS). For the purpose of this guide, we use Snort as the IDS.`

to 

`You can use Ansible to automate your Intrusion Detection and Prevention System (IDPS). For the purpose of this guide, we use Snort as the IDPS.`

2021-09-28 20:24 UTC, lmalivert commented
Thanks for catching that @craig-br. Please review.

2021-09-29 10:51 UTC, craig-br commented
@lmalivert . It's ready to merge

2021-09-29 11:44 UTC, ariordan-redhat approved these changes
LGTM

2021-09-29 11:45 UTC, merged