AAP-3799 - Added Inclusive language statement to all documents
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #348
Opened 2022-06-03 22:25 UTC by dcdacosta

This PR adds the inclusive language module to all master.adoc files for the library. See https://issues.redhat.com/browse/AAP-3799.

2022-06-07 10:04 UTC, oraNod commented on downstream/titles/aap-installation-guide/master.adoc
> +include::../../../common/making-open-source-more-inclusive.adoc[]
Should create a symlink to the common folder in each directory so the include directive is like this: `include::common/making-open-source-more-inclusive.adoc[]`

The publishing system doesn't play nicely with `../` (although that might have changed).

2022-06-07 10:05 UTC, oraNod commented on downstream/titles/aap-installation-guide/master.adoc
> +include::../../../common/making-open-source-more-inclusive.adoc[]
@dcdacosta Give me a shout if you want me to create the symlinks. I don't mind doing it. Also what do you think about changing `common` to `aap-common`?

2022-06-09 10:00 UTC, ariordan-redhat reviewed
@dcdacosta 

I can't build the docs because `context` isn't defined for `common/making-open-source-more-inclusive.adoc`

```
[id="making-open-source-more-inclusive_{context}"]
```

Do we need the context included for this module?

The build was successful for me when I deleted `_{context}` from the module ID (`[id="making-open-source-more-inclusive"]`)

It was also successful when I defined `context` before the `id=` line:

```
:context: common
[id="making-open-source-more-inclusive_{context}"]
```

One other point: The nesting in the index looks wrong in my build when the inclusive module is added:

![image](https://user-images.githubusercontent.com/44700011/172821573-2451eb64-7b88-4c6a-aec9-d510cbd17889.png)

Is there a way to change this?

2022-06-09 17:09 UTC, dcdacosta commented
> @dcdacosta
> 
> I can't build the docs on my machine (a Mac) because `context` isn't defined for `common/making-open-source-more-inclusive.adoc`
> 
> ```
> [id="making-open-source-more-inclusive_{context}"]
> ```
> 
> Do we need the context included for this module?
> 
> The build was successful for me when I deleted `_{context}` from the module id line:
> 
> ```
> [id="making-open-source-more-inclusive"]
> ```
> 
> It was also successful when I defined `context` before the `id=` line:
> 
> ```
> :context: common
> [id="making-open-source-more-inclusive_{context}"]
> ```
> 
> One other point: The nesting in the index looks wrong in my build when the `common/making-open-source-more-inclusive.adoc` module is added:
> 
> ![common_module](https://user-images.githubusercontent.com/44700011/172821829-144ec5cd-df6c-4f85-940e-afa547bbcaae.jpg)
> 
> Is there a way to change this?

Hi @ariordan-redhat My bad, I'll fix the context issue. I'm not sure how to fix the index issue but I'll put a shoutout in the CCS gchat space to see if anyone knows what I can do. Thanks for the feedback!

2022-06-09 17:30 UTC, oraNod commented
What about creating an `assembly-aap.adoc` file that we set as the preface?

The assembly could include a brief concept module that explains AAP from a high level, the inclusive language initiative, and a pointer to the downloads page + any other standard content that could be included in every `master.adoc` file.

Here's an example for RHDG: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.3/html/red_hat_data_grid_8.3_release_notes/red-hat-data-grid

2022-06-09 17:47 UTC, ariordan-redhat commented
There is a way to escape an asciidoc heading from being indexed, but I don't know whether the Pantheon build supports it:
```
[discrete]
= Making open source more inclusive
```
<img width="619" alt="image" src="https://user-images.githubusercontent.com/44700011/172911324-2687bd6a-b42b-41b7-b33e-4e24b1fece9c.png">


<img width="718" alt="image" src="https://user-images.githubusercontent.com/44700011/172911256-58ae5747-dd63-4346-af40-d12d7dd0ee75.png">

2022-06-09 18:48 UTC, oraNod commented
Yes, Pantheon plays nicely with the `[discrete]` tag.

2022-06-09 18:55 UTC, dcdacosta commented
Ah yes, I forgot about the discrete tag. I think I'll switch to using that for now and we can revisit the other options as a team later. Thanks @oraNod and @ariordan-redhat!

2022-06-13 15:46 UTC, ariordan-redhat requested changes
@dcdacosta 
I wrote a quick and clunky script to build all the docs. 
Everything built OK apart from the release notes; I added a suggestion for fixing this.

One doc (`analytics/automation-savings-planner/`)doesn't have a title in the first assembly (`analytics/assembly-automation-savings-planner.adoc`), so the nesting looked wrong. I'll take care of this in another PR: it's out of scope for this PR.

2022-06-15 15:09 UTC, oraNod commented
Thanks for the work here @dcdacosta I'm going to close this PR as discussed to move the inclusive language statement to a dedicated branch for boilerplate and other common content that we can use across releases.

2022-06-15 15:09 UTC, closed without merging