AAP-2948 Add step to activate AAP repo
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #546
Opened 2022-09-22 03:45 UTC by jself-sudoku

Added a new first step in the **Ansible Builder Guide** in "Chapt 2.1 Installing Ansible Builder"  to activate the AAP repo.

2022-09-26 15:49 UTC, msilmser requested changes
The full command to enable that repo is:

dnf config-manager --enable ansible-automation-platform-2.1-for-rhel-8-x86_64-rpms

2022-09-27 21:18 UTC, jself-sudoku commented
> The full command to enable that repo is:
> 
> dnf config-manager --enable ansible-automation-platform-2.1-for-rhel-8-x86_64-rpms

2022-09-27 21:19 UTC, jself-sudoku commented
@msilmser - corrected the command. Please review.

2022-09-28 14:04 UTC, msilmser approved these changes

2022-10-03 22:19 UTC, merged