AAP-357 added links to builder and navigator guides
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #656
Opened 2022-11-29 11:50 UTC by emurtoug

1. modules/dev-guide/con-content-workflows.adoc:

**Under Additional resources**
Added links to [Ansible Navigator Creator Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/ansible_navigator_creator_guide) and [Creating and Consuming Execution Environments](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/creating_and_consuming_execution_environments/index).

2. modules/core/execution-environments.adoc:

**Under Additional resources**
Added link to [Creating and Consuming Execution Environments](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/creating_and_consuming_execution_environments/index).

2022-11-29 13:30 UTC, ariordan-redhat requested changes
Looks like the `{` and `}` characters were rendered weirdly.

2022-11-29 13:30 UTC, ariordan-redhat commented on downstream/modules/dev-guide/con-content-workflows.adoc
> +* For more information on {Builder}, see link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/creating_and_consuming_execution_environments/i
Suggestion: remove the `////` comment lines before and after the additional resources content

2022-11-29 14:10 UTC, emurtoug commented on downstream/modules/dev-guide/con-content-workflows.adoc
> +* For more information on {Builder}, see link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/creating_and_consuming_execution_environments/i
Thanks, Aine! That's done now.

2022-11-29 14:11 UTC, emurtoug commented on downstream/modules/core/con-execution-environments.adoc
>  ////
Thanks! I've fixed that issue with the { } characters now.

2022-11-29 23:07 UTC, ariordan-redhat commented on downstream/modules/core/con-execution-environments.adoc
>  * Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-gui
```suggestion
```

2022-11-30 17:56 UTC, ariordan-redhat approved these changes
Doc built OK and links are valid.
Looks good to me.

2022-12-01 09:33 UTC, merged