AAP-7870 updated installation guide
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #717
Opened 2023-01-03 17:41 UTC by emurtoug

Updated [1] [proc-installing-the-aap-setup-bundle.adoc](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/disconnected-installation#installing_the_setup_bundle) and [2] p[roc-synchronizing-rpm-repositories-by-using-reposync.adoc](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/disconnected-installation#proc-synchronizing-rpm-repositories-by-using-reposync_disconnected-installation) within the AAP Installation Guide

[1] Updated command to untar the bundle 
[2] Fixed git merge conflict

2023-01-05 17:35 UTC, dcdacosta approved these changes
/LGTM

2023-01-09 23:27 UTC, saito-hideki requested changes
Hi! 
Thank you for the PR! I left a comment regarding the version notation. :)

2023-01-09 23:27 UTC, saito-hideki commented on downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
> +   ansible-automation-platform-setup-bundle-2.3.tar.gz
Hi,

It seems that the latest version setup-bundle is `ansible-automation-platform-setup-bundle-2.3-1.1.tar.gz`. So you need to relate 2.3 with 2.3-1.1 if you want to use the current setup-bundle version of 2.3 release.

Or you can use an abstract word, such as `ansible-automation-platform-setup-bundle-<RELEASE_VERSION>.tar.gz`. I would recommend this, although the user would need to replace it accordingly.

2023-01-09 23:27 UTC, saito-hideki commented on downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
> +$ cd ansible-automation-platform-setup-bundle-2.3-1
the same as above.

2023-01-19 16:40 UTC, dcdacosta approved these changes
LGTM

2023-01-19 16:40 UTC, merged