AAP-8221 - Refining Planning Guide structure
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #735
Opened 2023-01-12 00:39 UTC by dcdacosta

This PR addresses the changes required by https://issues.redhat.com/browse/AAP-8221.

Changes include:

- Restructuring the Guide from 1 large Chapter to 8 Chapters.
- Adding intro text where missing.

2023-01-12 10:45 UTC, ariordan-redhat commented
@dcdacosta I couldn't build this PR with bccutil. 
I opened a [PR](https://github.com/dcdacosta/red-hat-ansible-automation-platform-documentation/pull/1) against your topic branch with changes that I made to get bccutil working locally.

2023-01-18 11:37 UTC, ariordan-redhat requested changes
Typo in `leveloffset`; otherwise, LGTM

2023-01-18 11:37 UTC, ariordan-redhat commented on downstream/assemblies/platform/assembly-aap-platform-components.adoc
> +include::platform/con-overview-automation-mesh.adoc[leveloffet=+1]
```suggestion
include::platform/con-overview-automation-mesh.adoc[leveloffset=+1]
```

2023-01-18 16:25 UTC, lmalivert approved these changes

2023-01-18 20:10 UTC, dcdacosta commented on downstream/assemblies/platform/assembly-aap-platform-components.adoc
> +include::platform/con-overview-automation-mesh.adoc[leveloffet=+1]
Thank you! Fixed.

2023-01-19 10:08 UTC, ariordan-redhat approved these changes
LGTM

2023-01-19 10:10 UTC, merged