Section added on enabling the hstore extension
RedHatInsights/red-hat-ansible-automation-platform-documentation pull request #861
Opened 2023-02-15 15:18 UTC by ianf77

New procedure added to Planning Guide

Document 'hstore' extension requirement for customer provided database

https://issues.redhat.com/browse/AAP-8913

2023-02-17 11:38 UTC, EMcWhinn commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +Whete the default value for `<automation hub database>` is `automationhub`.
Should this be "Where"?

2023-02-17 11:42 UTC, EMcWhinn commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +This gives an output similar to the following
Should there be a colon after "the following"?

2023-02-17 11:52 UTC, EMcWhinn commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +. This indicates that `hstore` 1.7 extension is available, but not enabled.
Should there be an article before `hstore`, "... the `hstore`"?

2023-02-17 11:59 UTC, EMcWhinn commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +If the hstore extension is not available on the PostgreSQL server, the result is similar to the following:
For consistency should hstore be `hstore`?

2023-02-20 09:31 UTC, emurtoug requested changes
Just a couple fiddly comma placement suggestions, otherwise LGTM!

2023-02-20 09:31 UTC, emurtoug commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +. On a RHEL based server, the `hstore` extension is included in the `postgresql-contrib` RPM package which is not installed automatically when installing the PostgreSQL server RPM package.
Suggestion to add a comma in this line: 'RPM package**,** which is not'

2023-02-20 09:31 UTC, emurtoug commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +To install the RPM package use the following command:
Suggestion to add a comma in this line: 'package**,** use the'

2023-02-20 09:31 UTC, emurtoug commented on downstream/modules/platform/proc-enable-hstore-extension.adoc
> +. In the following output the `installed_version` field contains the `hstore` extension used, indicating that `hstore` is enabled.
Suggestion to add a comma in this line: 'output**,** the `installed_version`'

2023-02-20 09:41 UTC, emurtoug approved these changes
LGTM

2023-02-20 09:41 UTC, merged